apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-info-web
  labels:
    app: sys-info-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sys-info-web
  template:
    metadata:
      labels:
        app: sys-info-web
    spec:
      containers:
      - name: sys-info-web
        image: huajuan6848/sys-info-web:0.0.2-SNAPSHOT-HEALTH
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sys-info-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sys-info-web
---
apiVersion: v1
kind: Service
metadata:
  name: sys-info-web-dhcp
  annotations:
    kube-vip.io/loadbalancerHostname: sys-info-web-dhcp
spec:
  loadBalancerIP: 0.0.0.0
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sys-info-web